---
- hosts: servers
  become: true
  gather_facts: true
  name: Setup monitoring server
  roles:
    - { role: grafana, become: True, tags: grafana }
    - { role: prometheus, become: True, tags: prometheus }
...