---
- hosts: servers
  become: true
  gather_facts: true
  name: install and configure server
  roles:
    - { role: preparing, become: True, tags: preparing }
    - { role: docker, become: True, tags: docker_setup }