---
- name: Stop and Disable ufw service if started
  ansible.builtin.service:
    name: ufw
    state: stopped
    enabled: no

- name: Stop and Disable postfix service if started
  ansible.builtin.service:
    name: postfix
    state: stopped
    enabled: no
  ignore_errors: true

- name: Make timout configuration for inactive sessions.
  template:
    src: timout.j2
    dest: /etc/profile.d/timout-settings.sh

- name: Set timezone
  community.general.timezone:
    name: "{{timezone}}"
  notify: Restart ntp

- name: Copy ssh banner file.
  copy:
    src: ssh_banner
    dest: /etc/issue

- name: Remove execute permissions from MOTD scripts
  ansible.builtin.shell: "chmod -x /etc/update-motd.d/*"

- name: Make sshd configuration file.
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
  notify: Restart ssh

- name: Make iptables configuration file.
  template:
    src: iptables.j2
    dest: /etc/iptables/rules.v4

- name: restore iptables state from a file
  community.general.iptables_state:
    state: restored
    path: /etc/iptables/rules.v4
    noflush: true

- name: Restart iptables
  systemd:
    name: iptables
    state: restarted

- name: Make fail2ban configuration file.
  template:
    src: fial2ban.j2
    dest: /etc/fail2ban/jail.local
  notify: Restart fail2ban
...