---
- name: Config resolved
  ansible.builtin.template:
    src: resolved.conf.j2
    dest: /etc/systemd/resolved.conf
    backup: 'yes'
    mode: 0644
    owner: root
    group: root
  notify:
    - Reload systemd

- name: Config resolv
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    backup: 'yes'
    mode: 0644
    owner: root
    group: root
...