---
DIR_NAME: /deploy

TRAEFIK_IMAGE: traefik
TRAEFIK_VERSION: v3.2.3

DOMAIN_NAME: domain.tld
TRAEFIK_SUB_DOMAIN: sub

TRAEFIK_USERNAME: xxxxxxxx
TRAEFIK_PASSWORD: xxxxxxxxxxxx

TRAEFIK_ACME_EMAIL: mail@gmail.com
...