---
- name: Delete old grafana files
  ansible.builtin.file:
    state: absent
    path: "{{ DIR_NAME }}/grafana/grafana"

- name: Copy grafana files
  copy:
    src: grafana
    dest: "{{ DIR_NAME }}/grafana"

- name: Restart grafana services
  community.docker.docker_compose_v2:
    project_src: "{{ DIR_NAME }}/grafana"
    state: restarted
    files:
      - docker-compose.yaml
...